name: Unit tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: true
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "install dependencies"
        run: brew install svn unzip vladdoster/zunit/zunit zsh

      - name: "${{ matrix.test }}: ${{ matrix.os }}"
        run: zunit run --tap --verbose
